project:
  type: website
  output-dir: docs

website:
  title: "Bastazini"
  navbar:
    left:
      - href: index.qmd
        text: About
      - publications.qmd
      - people.qmd
      - professional.qmd
      - talks.qmd
      - media.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true